import { chromium } from 'playwright'
const b = await chromium.launch()
const pg = await b.newPage({ viewport: { width: 1440, height: 950 } })
// Reviews page (8 -> centered)
await pg.goto('https://www.shaggydogspa.com/reviews', { waitUntil: 'domcontentloaded', timeout: 45000 })
await pg.waitForTimeout(1500)
await pg.evaluate(()=>window.scrollBy(0,700)); await pg.waitForTimeout(400)
await pg.screenshot({ path: '_cB-reviews.png', animations:'disabled', timeout:15000 })
// Projects page (filter chips + centered gallery)
await pg.goto('https://www.shaggydogspa.com/projects', { waitUntil: 'domcontentloaded', timeout: 45000 })
await pg.waitForTimeout(1500)
const chips = await pg.evaluate(()=>[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(Boolean))
console.log('filter chips:', JSON.stringify(chips))
await pg.evaluate(()=>window.scrollBy(0,420)); await pg.waitForTimeout(400)
await pg.screenshot({ path: '_cB-projects.png', animations:'disabled', timeout:15000 })
console.log('done')
await b.close()
