/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    reviews: Review;
    certifications: Certification;
    'financing-options': FinancingOption;
    leads: Lead;
    bookings: Booking;
    blackouts: Blackout;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'financing-options': FinancingOptionsSelect<false> | FinancingOptionsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    blackouts: BlackoutsSelect<false> | BlackoutsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    branding: Branding;
    'home-page': HomePage;
    'financing-info': FinancingInfo;
    'availability-settings': AvailabilitySetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'financing-info': FinancingInfoSelect<false> | FinancingInfoSelect<true>;
    'availability-settings': AvailabilitySettingsSelect<false> | AvailabilitySettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL path segment. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  /**
   * One or two sentences shown on cards and previews.
   */
  summary: string;
  /**
   * Full service-page body.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "From $75" or "Add-on $25". Shown for transparency.
   */
  priceRange?: string | null;
  /**
   * Icon shown on the service card.
   */
  icon?: ('groom' | 'bath' | 'deshed' | 'nails' | 'flea' | 'cat') | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL path segment. Leave blank to auto-generate from the title.
   */
  slug?: string | null;
  service?: (number | null) | Service;
  city?: string | null;
  completedDate?: string | null;
  /**
   * Before photo.
   */
  beforeImage?: (number | null) | Media;
  /**
   * After photo (required).
   */
  afterImage: number | Media;
  /**
   * Additional photos for the project detail view.
   */
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  /**
   * Optionally tie this project to the customer review about it.
   */
  linkedReview?: (number | null) | Review;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  /**
   * Stars, 1–5.
   */
  rating: number;
  text: string;
  date?: string | null;
  /**
   * City/area.
   */
  location?: string | null;
  source?: ('Google' | 'Facebook' | 'Yelp' | 'Direct') | null;
  /**
   * Which service this review is about (optional).
   */
  service?: (number | null) | Service;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * What this trust point means for the customer (builds trust).
   */
  description?: string | null;
  /**
   * Link to the certifying body (optional).
   */
  link?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-options".
 */
export interface FinancingOption {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Price line, e.g. "From $75" or "Add-on $25".
   */
  terms?: string | null;
  partnerLogo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status?: ('new' | 'contacted' | 'scheduled' | 'closed') | null;
  name: string;
  phone: string;
  email?: string | null;
  /**
   * Service of interest.
   */
  service?: string | null;
  message?: string | null;
  /**
   * Where the request came from.
   */
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  status?: ('confirmed' | 'completed' | 'cancelled' | 'no-show') | null;
  /**
   * Slot key (YYYY-MM-DDTHH:mm).
   */
  slot: string;
  /**
   * Human-readable appointment time.
   */
  slotLabel?: string | null;
  name: string;
  phone: string;
  email?: string | null;
  service?: string | null;
  /**
   * Address where we’ll park and groom (the pet’s location).
   */
  address?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blackouts".
 */
export interface Blackout {
  id: number;
  /**
   * A day with no appointment availability.
   */
  date: string;
  /**
   * Optional note (e.g. Holiday).
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'financing-options';
        value: number | FinancingOption;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'blackouts';
        value: number | Blackout;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  priceRange?: T;
  icon?: T;
  image?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  service?: T;
  city?: T;
  completedDate?: T;
  beforeImage?: T;
  afterImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  linkedReview?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  rating?: T;
  text?: T;
  date?: T;
  location?: T;
  source?: T;
  service?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  description?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-options_select".
 */
export interface FinancingOptionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  terms?: T;
  partnerLogo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  message?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  status?: T;
  slot?: T;
  slotLabel?: T;
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  address?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blackouts_select".
 */
export interface BlackoutsSelect<T extends boolean = true> {
  date?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  /**
   * Main phone — used for click-to-call.
   */
  phone: string;
  /**
   * After-hours / text line (optional).
   */
  emergencyPhone?: string | null;
  email?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * One row per line, e.g. "Tue – Sat" / "9:00 AM – 6:00 PM".
   */
  hours?:
    | {
        days?: string | null;
        time?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    google?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    yelp?: string | null;
  };
  /**
   * State license number, if applicable.
   */
  license?: string | null;
  /**
   * Optional — leave blank if you’d rather not state it.
   */
  yearsInBusiness?: number | null;
  insuranceStatement?: string | null;
  /**
   * Average star rating (e.g. 4.9).
   */
  googleRating?: number | null;
  /**
   * Total review count.
   */
  googleReviewCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  /**
   * Primary logo (shown in the header on a light background).
   */
  logo?: (number | null) | Media;
  /**
   * Optional white/light logo for dark backgrounds (footer).
   */
  logoLight?: (number | null) | Media;
  /**
   * Browser tab icon (square PNG/SVG).
   */
  favicon?: (number | null) | Media;
  /**
   * Brand color (hex) — dark sections, headings.
   */
  primaryColor?: string | null;
  /**
   * Accent/CTA color (hex) — buttons.
   */
  accentColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    heading: string;
    subheading?: string | null;
    /**
     * Hero background photo (a happy, freshly groomed pet works best).
     */
    backgroundImage?: (number | null) | Media;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
  };
  /**
   * Short proof points shown under the hero.
   */
  trustBadges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  whyUs?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Toggle homepage sections on/off.
   */
  sections?: {
    showProjects?: boolean | null;
    showReviews?: boolean | null;
    showServiceAreas?: boolean | null;
    /**
     * Show the Packages & Pricing section.
     */
    showFinancing?: boolean | null;
  };
  finalCta?: {
    heading?: string | null;
    subheading?: string | null;
    ctaLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-info".
 */
export interface FinancingInfo {
  id: number;
  heading?: string | null;
  intro?: string | null;
  /**
   * Notes on pricing, add-ons, and what can affect the final quote.
   */
  insuranceClaimHelp?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-settings".
 */
export interface AvailabilitySetting {
  id: number;
  days?: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[] | null;
  /**
   * First slot (24h, e.g. 08:00).
   */
  startTime?: string | null;
  /**
   * Slots end before this (24h, e.g. 16:00).
   */
  endTime?: string | null;
  /**
   * Slot length (minutes).
   */
  slotMinutes?: number | null;
  /**
   * Max appointments per slot (vans/groomers).
   */
  capacityPerSlot?: number | null;
  /**
   * How far ahead bookable (weeks).
   */
  weeksAhead?: number | null;
  /**
   * Minimum notice before a slot can be booked (hours).
   */
  minLeadHours?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  phone?: T;
  emergencyPhone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  social?:
    | T
    | {
        google?: T;
        facebook?: T;
        instagram?: T;
        yelp?: T;
      };
  license?: T;
  yearsInBusiness?: T;
  insuranceStatement?: T;
  googleRating?: T;
  googleReviewCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  logo?: T;
  logoLight?: T;
  favicon?: T;
  primaryColor?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        backgroundImage?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
      };
  trustBadges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  whyUs?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        showProjects?: T;
        showReviews?: T;
        showServiceAreas?: T;
        showFinancing?: T;
      };
  finalCta?:
    | T
    | {
        heading?: T;
        subheading?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-info_select".
 */
export interface FinancingInfoSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  insuranceClaimHelp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-settings_select".
 */
export interface AvailabilitySettingsSelect<T extends boolean = true> {
  days?: T;
  startTime?: T;
  endTime?: T;
  slotMinutes?: T;
  capacityPerSlot?: T;
  weeksAhead?: T;
  minLeadHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}